# .github/labeler.yml

Standard-Change:
- changed-files:
  - any-glob-to-any-file: '.github/**'
  - any-glob-to-any-file: '.scaffold/**'
  - any-glob-to-any-file: '.mill-version'
  - any-glob-to-any-file: 'mill-build/**'
  - any-glob-to-any-file: '**/Makefile'
  - any-glob-to-any-file: '**/*.nix'
  - any-glob-to-any-file: '**/*.sc'
  - any-glob-to-any-file: '**/*.sh'


  
