# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

############################# ETX Makefile Magic ##############################
### !!!!!!!!!!!!!!!!!!!!!!!! DO NOT EDIT THIS FILE ¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡ ###
###############################################################################

## Force shell to bash to ensure we run the nix provided bash shell for all shell scripts:
export SHELL := $(shell which bash)

## Colours for shell output:
GREEN := \033[0;32m
NC    := \033[0m
RED   := \033[0;31m

## Discover nested Makefiles in project:
NESTED_MAKEFILES := $(shell find . -type f -name Makefile | grep -v '\./Makefile' | egrep -v '(.venv|.scaffold)' | sed 's|\./||g' | sed 's/Makefile//g' | sort)
## Make a list of paths for all discovered Makefiles
NESTED_MAKEFILE_DIRS := $(patsubst %Makefile,%,$(NESTED_MAKEFILES))
## Generate a list of all documented targets in all discovered Makefiles
ALL_DOCUMENTED_TARGETS := $(shell for dir in ${NESTED_MAKEFILE_DIRS}; do for i in `grep -E '^[\.a-zA-Z_-]+:.*?## .*$$' $${dir}/Makefile | awk 'BEGIN {FS = ":.*?## "}; {printf "%s\n", $$1}'`; do printf "$${dir}$${i} "; done; done)


###############################################################################
### Functions #################################################################
###############################################################################

## Print environment information for assisting with debugging:
define env-debug
	echo "### Tooling Check:"
	echo "[INFO] shell path: ${SHELL}"
	echo "[INFO] shell version: `${SHELL} --version | head -1`"
	echo "[INFO] host info: `uname -o -m -r`"
	for tool in nix direnv; do \
		tool_path=`command -v $${tool}`; \
		if [ -z $${tool_path} ]; then \
			echo "[WARN] $${tool} path: $${tool} not found in shell path"; \
		else \
			echo "[INFO] $${tool} path: $${tool_path}"; \
			echo "[INFO] $${tool} version: `$${tool} --version | head -1`"; \
		fi \
	done
	echo "[INFO] direnv dir check: `declare -p DIRENV_DIR 2> /dev/null || echo 'DIRENV_DIR not declared in env'`"
	echo "[INFO] direnv file check: `declare -p DIRENV_FILE 2> /dev/null || echo 'DIRENV_FILE not declared in env'`"
endef

## Run a make target in a sub directory:
## $(1) == path of directory to Makefile
## $(2) == make targets to pass
##   Notes:
##     - make is invoked with '-e' so all variables passed in are exposed in the environment
##       - this was done to make the abstraction "cleaner"
##
define run-make-in
	@if [ $(1) == '.' ]; then echo -e "[${RED}ERROR${NC}] target $(1)/$(2) is malformed, documented project targets by running 'make help', exiting..."; exit 1;fi
    @if [ ! -f $(1)/Makefile ]; then echo -e "[${RED}ERROR${NC}] directory '$(1)/' does not exist or contain a Makefile, please refer to documented project targets by running 'make help', exiting..."; exit 1;fi
	$(MAKE) -e -C $(1) $(2)
endef

## Parse repositories Makefile's and render help docstrings relevant to root of project:
## $(1) == list of directories that contains Makefiles to be parsed
##
define render-help
	echo -e "## ${GREEN}Project Make Targets${NC} ##\\n\\n"; \
	printf "### Top Level Helpers:\\n"
	grep -E '^[\.a-zA-Z_-]+:.*?## .*$$' "./Makefile" | sort | sed "s|^|$${MAKE_DIR}|g" | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-50s\033[0m %s\n", $$1, $$2}'
	printf '\n'
	for MAKE_DIR in $(1); do \
	printf "### Discovered Targets: $${MAKE_DIR}\\n"; \
	grep -E '^[\.a-zA-Z_-]+:.*?## .*$$' "$${MAKE_DIR}/Makefile" | sort | sed "s|^|$${MAKE_DIR}|g" | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-50s\033[0m %s\n", $$1, $$2}'; \
	printf '\n'; \
	done
endef

## Dynamically generate targets based on presence of docstring in discovered nested Makefiles
## $(1) == path of discovered Makefile with target appended
##
define documented_target_creation
.PHONY: $(1)

$(1):
	@$$(call run-make-in,$$(@D),$$(@F))
endef

###############################################################################
### Targets ###################################################################
###############################################################################

default: help

.PHONY: help
help: ## print all documented make targets in repository
	@$(call render-help,$(NESTED_MAKEFILE_DIRS))

.PHONY: debug
debug: ## print environment debug information
	@$(call env-debug)
	@echo "[INFO] nested make file locations: $(NESTED_MAKEFILE_DIRS)"
	@echo "[INFO] all documented targets: $(ALL_DOCUMENTED_TARGETS)"


.PHONY: copyright-check
copyright-check: ## check copyright notices for all files in the project
	@python3 .scaffold/libs/python/copyright-headers.py \
		--config-file .scaffold/libs/python/copyright-headers.json \
		--action check

.PHONY: copyright-update
copyright-update: ## update missing copyright notices for all files in the project
	@python3 .scaffold/libs/python/copyright-headers.py \
		--config-file .scaffold/libs/python/copyright-headers.json \
		--action update


## Discovered Targets:
## The following is designed to generate all documented targets found in sub folders:
##   - target defaults to passing the directory to run-make-in as a potentional path for a Makefile
##   - the "file" at the end of the target path is passed as the target to execute
##   - any variables in the environment or delcared at run time are exposed in the subsequent make invocation
##
## Notes:
##   - tab completion for generated targets may not work depending on the tab completion logic used for gnumake
##
$(foreach target,$(ALL_DOCUMENTED_TARGETS),$(eval $(call documented_target_creation,$(target))))

## Catch-all for all undocumented nested targets:
##  The following is a catch-all target, this is here to to allow for operators to run undocumented targets in nested Makefiles
##
%:
	$(call run-make-in,$(@D),$(@F))
