# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

############################# ETX Makefile Magic ##############################
### !!!!!!!!!!!!!!!!!!!!!!!! DO NOT EDIT THIS FILE ¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡ ###
###############################################################################

## Force shell to bash to ensure we run the nix provided bash shell for all shell scripts:
export SHELL := $(shell which bash)

## Colours for shell output:
GREEN := \033[0;32m
NC    := \033[0m
RED   := \033[0;31m

## Discover nested Makefiles in project:
NESTED_MAKEFILES := $(shell find . -type f -name Makefile | grep -v '\./Makefile' | egrep -v '(.venv|.scaffold)' | sed 's|\./||g' | sed 's/Makefile//g' | sort)
## Make a list of paths for all discovered Makefiles
NESTED_MAKEFILE_DIRS := $(patsubst %Makefile,%,$(NESTED_MAKEFILES))
## Generate a list of all documented targets in all discovered Makefiles
ALL_DOCUMENTED_TARGETS := $(shell for dir in ${NESTED_MAKEFILE_DIRS}; do for i in `grep -E '^[\.a-zA-Z_-]+:.*?## .*$$' $${dir}/Makefile | awk 'BEGIN {FS = ":.*?## "}; {printf "%s\n", $$1}'`; do printf "$${dir}$${i} "; done; done)

## Mill
MILL_OPTS ?=
FUNC_TEST_CONTROLS ?=

## Disable Mill server in CI:
ifeq ($(CI),true)
MILL_OPTS := --no-server $(MILL_OPTS)
endif

###############################################################################
### Functions #################################################################
###############################################################################

## Print environment information for assisting with debugging:
define env-debug
	echo "### Tooling Check:"
	echo "[INFO] shell path: ${SHELL}"
	echo "[INFO] shell version: `${SHELL} --version | head -1`"
	echo "[INFO] host info: `uname -o -m -r`"
	for tool in nix direnv; do \
		tool_path=`command -v $${tool}`; \
		if [ -z $${tool_path} ]; then \
			echo "[WARN] $${tool} path: $${tool} not found in shell path"; \
		else \
			echo "[INFO] $${tool} path: $${tool_path}"; \
			echo "[INFO] $${tool} version: `$${tool} --version | head -1`"; \
		fi \
	done
	echo "[INFO] direnv dir check: `declare -p DIRENV_DIR 2> /dev/null || echo 'DIRENV_DIR not declared in env'`"
	echo "[INFO] direnv file check: `declare -p DIRENV_FILE 2> /dev/null || echo 'DIRENV_FILE not declared in env'`"
endef

## Run a make target in a sub directory:
## $(1) == path of directory to Makefile
## $(2) == make targets to pass
##   Notes:
##     - make is invoked with '-e' so all variables passed in are exposed in the environment
##       - this was done to make the abstraction "cleaner"
##
define run-make-in
	@if [ $(1) == '.' ]; then echo -e "[${RED}ERROR${NC}] target $(1)/$(2) is malformed, documented project targets by running 'make help', exiting..."; exit 1;fi
    @if [ ! -f $(1)/Makefile ]; then echo -e "[${RED}ERROR${NC}] directory '$(1)/' does not exist or contain a Makefile, please refer to documented project targets by running 'make help', exiting..."; exit 1;fi
	$(MAKE) -e -C $(1) $(2)
endef

## Parse repositories Makefile's and render help docstrings relevant to root of project:
## $(1) == list of directories that contains Makefiles to be parsed
##
define render-help
	echo -e "## ${GREEN}Project Make Targets${NC} ##\\n\\n"; \
	printf "### Top Level Helpers:\\n"
	grep -E '^[\.a-zA-Z_-]+:.*?## .*$$' "./Makefile" | sort | sed "s|^|$${MAKE_DIR}|g" | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-50s\033[0m %s\n", $$1, $$2}'
	printf '\n'
	for MAKE_DIR in $(1); do \
	printf "### Discovered Targets: $${MAKE_DIR}\\n"; \
	grep -E '^[\.a-zA-Z_-]+:.*?## .*$$' "$${MAKE_DIR}/Makefile" | sort | sed "s|^|$${MAKE_DIR}|g" | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-50s\033[0m %s\n", $$1, $$2}'; \
	printf '\n'; \
	done
endef

## Dynamically generate targets based on presence of docstring in discovered nested Makefiles
## $(1) == path of discovered Makefile with target appended
##
define documented_target_creation
.PHONY: $(1)

$(1):
	@$$(call run-make-in,$$(@D),$$(@F))
endef

###############################################################################
### Targets ###################################################################
###############################################################################

default: help

.PHONY: help
help: ## print all documented make targets in repository
	@$(call render-help,$(NESTED_MAKEFILE_DIRS))

.PHONY: debug
debug: ## print environment debug information
	@$(call env-debug)
	@echo "[INFO] nested make file locations: $(NESTED_MAKEFILE_DIRS)"
	@echo "[INFO] all documented targets: $(ALL_DOCUMENTED_TARGETS)"


.PHONY: copyright-check
copyright-check: ## check copyright notices for all files in the project
	@python3 .scaffold/libs/python/copyright-headers.py \
		--config-file .scaffold/libs/python/copyright-headers.json \
		--action check

.PHONY: copyright-update
copyright-update: ## update missing copyright notices for all files in the project
	@python3 .scaffold/libs/python/copyright-headers.py \
		--config-file .scaffold/libs/python/copyright-headers.json \
		--action update

###############################################################################
## Generate version for builds ################################################
###############################################################################

## Populate and export PQS_VERSION with generated details above:
## - use svu to generate SemVer compliant version value
##   - increments patch value from most recent release tag

## - Mill sets version in application from PQS_VERSION env var
export PQS_VERSION ?= $(shell _gen_build_version)

.PHONY: version
version:
	@echo "[INFO] build number: ${PQS_VERSION}"

###############################################################################
## Documented Targets #########################################################
###############################################################################

.PHONY: auth.test
auth.test:
	mill ${MILL_OPTS} auth.test

.PHONY: check-scala-format
check-scala-format: ## Scalafmt check
	mill ${MILL_OPTS} __.checkFormat

.PHONY: reformat-scala
reformat-scala: ## Reformat scala
	mill ${MILL_OPTS} __.reformat

.PHONY: bsp
bsp: ## Setup Mill-BSP (Build Server Protocol) bridge
	mill ${MILL_OPTS} mill.bsp.BSP/install

.PHONY: idea
idea: bsp ## Open project in IntelliJ IDEA
	idea .

.PHONY: clean
clean: ## Clean build outputs
	mill ${MILL_OPTS} clean

.PHONY: stop
stop: ## Stop running servers
	mill ${MILL_OPTS} __.stop

.PHONY: build
build: ## Compile all modules
	mill ${MILL_OPTS} __.checkFormat
	mill ${MILL_OPTS} pqs.jar

.PHONY: package
package: ## Package artifacts
	mill ${MILL_OPTS} pqs.assembly

.PHONY: test
test: auth.test ## Unit test all modules
	mill ${MILL_OPTS} __.test.test

.PHONY: func-test
func-test: package ## Run all (expensive) functional tests
	mill ${MILL_OPTS} -k -j 1 pqs.functest.test ${FUNC_TEST_CONTROLS}

.PHONY: consolidate-test-results
consolidate-test-results: ## Consolidate all test results in one folder
	rm -rf out/tests
	mkdir -p out/tests
	cp -v --parents `find out -path "*/test*.dest/results.xml"` out/tests

.PHONY: updates
updates: ## Show available updates for used libraries
	mill ${MILL_OPTS} mill.scalalib.Dependency/showUpdates

.PHONY: prefetch-deps
prefetch-deps: ## Fetch all dependencies for offline operations
	mill ${MILL_OPTS} _.prepareOffline + __.prepareOffline

.PHONY: populate-dist-dir
populate-dist-dir: ## Create and populate .dist/ directory with pqs.jar
	mkdir -p .dist/${PQS_VERSION}/
	cp -v out/pqs/assembly.dest/out.jar .dist/${PQS_VERSION}/pqs.jar

.PHONY: populate-blackduck-dir
populate-blackduck-dir:
	mill pqs.pom
	mkdir -p .blackduck-input/${PQS_VERSION}/
	cp -v out/pqs/pom.dest/pom.xml .blackduck-input/${PQS_VERSION}/pom.xml

###############################################################################
## Matrix Compatibility Tests #################################################
###############################################################################

.PHONY: matrix-test
matrix-test: ## run matrix compatibility test tool use MATRIX_TEST_ARGS to pass arguments
	modules/compatibility/run-compatibility-tests.sh ${MATRIX_TEST_ARGS}

validate-matrix-workflow: ## ensure test count in parameters.csv and GHA config match
	modules/compatibility/run-compatibility-tests.sh -v

render-matrix-workflow: ## renders .github/workflow/matrix-compatibility-test.yml
	modules/compatibility/run-compatibility-tests.sh -r

###############################################################################
## DPM Assistant Publishing Stuff #############################################
###############################################################################

ASSISTANT_ARGS ?= oci://europe-docker.pkg.dev/da-images/playground/components

.PHONY: populate-component-yaml
populate-component-yaml: ## Render dpm component.yaml
	cp LICENSE.txt .dist/${PQS_VERSION}/LICENSE
	@printf 'apiVersion: digitalasset.com/v1\nkind: Component\nspec:\n  jar-commands:\n    - path: ./pqs.jar\n      name: pqs\n      desc: participant query store\n' \
		| tee .dist/${PQS_VERSION}/component.yaml

.PHONY: publish-component
publish-component: ## publish dpm component
	dpm publish component \
		-p generic=.dist/${PQS_VERSION}/ $(ASSISTANT_ARGS)/participant-query-store:$(patsubst v%,%,$(PQS_VERSION)) \
		--extra-tags 3.6
	dpm publish component \
		-p generic=.dist/${PQS_VERSION}/ $(ASSISTANT_ARGS)/scribe:$(patsubst v%,%,$(PQS_VERSION)) \
		--extra-tags 3.6

## Discovered Targets:
## The following is designed to generate all documented targets found in sub folders:
##   - target defaults to passing the directory to run-make-in as a potentional path for a Makefile
##   - the "file" at the end of the target path is passed as the target to execute
##   - any variables in the environment or delcared at run time are exposed in the subsequent make invocation
##
## Notes:
##   - tab completion for generated targets may not work depending on the tab completion logic used for gnumake
##
$(foreach target,$(ALL_DOCUMENTED_TARGETS),$(eval $(call documented_target_creation,$(target))))

## Catch-all for all undocumented nested targets:
##  The following is a catch-all target, this is here to to allow for operators to run undocumented targets in nested Makefiles
##
%:
	$(call run-make-in,$(@D),$(@F))
