// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.digitalasset.scribe.postgres.document

import com.digitalasset.auth
import com.digitalasset.auth.{Auth, TokenService}
import com.digitalasset.canonical.{ContractFilter, given}
import com.digitalasset.scribe.app.*
import com.digitalasset.scribe.configuration
import com.digitalasset.scribe.logging.FileLogging
import com.digitalasset.scribe.postgres.{backend, document}
import com.digitalasset.transcode.schema.IdentifierFilter
import com.digitalasset.zio.daml
import com.digitalasset.zio.daml.{DamlSchema, FileCache, LedgerScope}
import zio.Console.printLine
import zio.ZIO.{logInfo, logTrace, serviceWithZIO}
import zio.config.magnolia.{Descriptor, describe}
import zio.{ZIO, ZLayer}

object Main extends ComposableApp:
  def app =
    "postgres-document"
      @@ Command("Perform operations supporting Postgres database (w/ document payload representation)")
      - (appSchema | appPrune)

  private def appSchema =
    "schema" @@ Command("Infer or apply database schema derived from Daml package metadata")
      - (appSchemaApply | appSchemaShow)

  private def appSchemaApply = (
    "apply" @@ Command("Infer required database schema, apply it to data store and quit")
      - cliConfig[ConfigSchemaApply]
      `map` applySchema
  )

  private def appSchemaShow = (
    "show" @@ Command("Infer required database schema, display it and quit")
      - cliConfig[ConfigSchemaShow]
      `map` showSchema
  )

  private def appPrune = (
    "prune" @@ Command("Prune transactions to a given offset inclusively")
      - cliConfig[ConfigPrune]
      `map` prune
  )

  @SuppressWarnings(Array("org.wartremover.warts.AsInstanceOf"))
  private def applySchema(config: ZLayer[Any, Throwable, ConfigSchemaApply]) =
    (for
      _          <- logInfo("Applying required datastore schema")
      config     <- ZIO.service[backend.SchemaConfig]
      poolConfig <- ZIO.service[backend.PostgresConfig]
      instanceId <- ZIO.service[backend.InstanceId]
      _          <- document.DocumentPostgres.applySchema(poolConfig, instanceId, config.baseline)
      _          <- logInfo("Applied required datastore schema")
      _          <- printLine("Finished applying schema to datastore")
    yield ())
      .provide(
        com.digitalasset.scribe.appversion.LogVersion,
        (config.project(_.ledger.auth) ++ config.project(_.oauth)) >>> Auth.live(LedgerScope),
        TokenService.live,
        config.project(_.ledger) >>> daml.Channel.live,
        config.project(_.ledger) >>> FileCache.live,
        config.project(_.postgres),
        config.project(_.schema),
        backend.instanceId,
        backend.connectionPool,
        DamlSchema.schema,
        config.project(_.filter.contracts),
        DamlSchema.produce(document.SqlSchema)
      )
      .bootstrap(
        config.project(_.logger).orElse(FileLogging.default) >>> com.digitalasset.scribe.cli.bootstrap
      )

  private def showSchema(config: ZLayer[Any, Throwable, ConfigSchemaShow]) =
    serviceWithZIO[document.SqlSchema.Service] { s =>
      logInfo("Displaying required datastore schema") *>
        logTrace(s"Schema:${System.lineSeparator}${s.schema}") *>
        logTrace(s"Mappings:${System.lineSeparator}${s.mappings}") *>
        printVersionHeader *> printLine(s.schema) *> printLine(s.mappings)
    }
      .provide(
        com.digitalasset.scribe.appversion.LogVersion,
        (config.project(_.ledger.auth) ++ config.project(_.oauth)) >>> Auth.live(LedgerScope),
        TokenService.live,
        config.project(_.ledger) >>> daml.Channel.live,
        config.project(_.ledger) >>> FileCache.live,
        DamlSchema.schema,
        config.project(_.filter.contracts),
        DamlSchema.produce(document.SqlSchema)
      )
      .bootstrap(
        config.project(_.logger).orElse(FileLogging.default) >>> com.digitalasset.scribe.cli.bootstrap
      )

  private def prune(config: ZLayer[Any, Throwable, ConfigPrune]) =
    serviceWithZIO[document.Prune.Service](_.run)
      .provide(
        com.digitalasset.scribe.appversion.LogVersion,
        config.project(_.prune) >>> Prune.layer,
        config.project(_.postgres) >+> backend.instanceId >>> backend.connectionPool
      )
      .bootstrap(
        config.project(_.logger).orElse(FileLogging.default) >>> com.digitalasset.scribe.cli.bootstrap
      )

  private val printVersionHeader = com.digitalasset.scribe.appversion.getVersion.flatMap {
    case (title, version, _) =>
      val content        = s"generated by $title, version: $version"
      val commentOpening = "/" + "*" * (content.length + 4)
      ZIO.foreach(List(commentOpening, " * " + content + " *", " " + commentOpening.reverse))(printLine(_))
  }

  private final case class ConfigSchemaShow(
      ledger: daml.Config,
      oauth: auth.Config.OAuth,
      filter: Filters = Filters(),
      logger: FileLogging.Config
  )

  private final case class ConfigSchemaApply(
      ledger: daml.Config,
      oauth: auth.Config.OAuth,
      postgres: backend.PostgresConfig,
      schema: backend.SchemaConfig,
      filter: Filters = Filters(),
      logger: FileLogging.Config
  )

  private final case class ConfigPrune(
      prune: Prune.Config,
      postgres: backend.PostgresConfig,
      logger: FileLogging.Config
  )

  private final case class Filters(
      @describe("Filter expression determining which templates and interfaces to include")
      contracts: ContractFilter = ContractFilter(IdentifierFilter.AcceptAll)
  )
end Main
