#!/usr/bin/env bash
# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

## Use some shared output/formatting things:
REPO_ROOT=$(git rev-parse --show-toplevel)
source ${REPO_ROOT}/.scaffold/libs/bash/shared_functions

## Defaults
HEADER='Scribe Matrix Test Runner v2'
PARAMS_CSV="${REPO_ROOT}/modules/compatibility/parameters.csv"
LOG_DIR="${REPO_ROOT}/modules/compatibility/log"
WORKFLOW_FILE="${REPO_ROOT}/.github/workflows/matrix-compatibility-test.yml"
declare -a FUNC_TEST_CONTROLS='()'

## Get total number of entries in param csv file:
line_count=$(tail -n+2 "${PARAMS_CSV}" | grep -v '^#'| wc -l)
declare -a lines='()'

function render_help() {
  echo "  matrix testing tool for functional testing, available options:"
  echo ""

  print_help_item "-c|count" \
    "prints the number of tests defined in ${PARAMS_CSV}"

  print_help_item "-r|render_workflow" \
    "render GitHub Actions workflow based on tests defined in ${PARAMS_CSV}"

  print_help_item "[1-9][0-9]" \
    "executes the test line(s) numbers provided"

  print_help_item "all" \
    "executes all defined tests in ${PARAMS_CSV}"

  print_help_item "-d|dryrun" \
    "execute script in dryrun mode, will not run matrix tests"

  print_help_item "-l|lanes" \
    "control the number of lanes the func-test runner will use [optional]"

  print_help_item "-p|pools" \
    "control the number of pools the func-test runner will use [optional]"

  print_help_item "-h|help" \
    "you are reading it"

}

function generate_worfklow_config() {
    YEAR=$(date +%Y)
    local test_numbers=$(seq 1 ${1} | paste -sd, - | sed 's/,/, /g')

cat << EOF
# Copyright (c) ${YEAR}, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

## NOTE: file is generated by running '${0} -r', do not edit manually!

name: Matrix Compatibility
on:
  push:
    branches:
      - main
      - 'release-line-*'
  workflow_dispatch: # Enables manual triggering

env:
  MILL_OPTS: "-Dcoursier.cache.dir=/data/coursier"

defaults:
  run:
    shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail {0}"

jobs:
  build:
    runs-on: digital-asset-participant-query-store
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/nix
      - run: make prefetch-deps
      - name: Build & Package
        run: make build package
      - name: Store Mill outputs
        uses: actions/upload-artifact@v7
        with:
          path: out
          retention-days: 7

  matrix-test:
    name: Matrix Test \${{ matrix.test-number }}
    needs: build
    runs-on: digital-asset-participant-query-store
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        test-number: [${test_numbers}]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/nix
      - uses: ./.github/actions/matrix-compatibility-test
        with:
          test-number: \${{ matrix.test-number }}
EOF
}

## arg handling:
while [[ $# -gt 0 ]]; do
    case "$1" in
        -d|dryrun|--dryrun)
            DRYRUN=true
            shift
            ;;
        -l|lanes|--lanes)
            FUNC_TEST_CONTROLS+=('--lanes' "${2}")
            shift 2
            ;;
        -p|pools|--pools)
            FUNC_TEST_CONTROLS+=('--pools' "${2}")
            shift 2
            ;;
        all)
            for line in $(seq 1 ${line_count}); do
              lines+=("${line}")
            done
            shift
            ;;
        -c|count|--count)
            echo "${line_count}"
            exit 0
            ;;
        -r|render_workflow|--render_workflow)
            _print_header "${HEADER}"
            _log_info "generating matrix test workflow defintion:"
            _log_info_item "GitHub Actions workflow: ${WORKFLOW_FILE}"
            _log_info_item "matrix parameters: ${PARAMS_CSV}"
            _log_progress_start "rendering Github Actions workflow with ${line_count} matrix tests:"
            generate_worfklow_config ${line_count} > ${WORKFLOW_FILE}
            _log_progress_done
            if [[ $(git diff -s --exit-code ${WORKFLOW_FILE}) == 0 ]]; then
                _log_info "no changes have been made to the workflow..."
            else
                _log_info "changes have been made to the workflow, please review and commit them:"
                _log_info_item "git diff ${WORKFLOW_FILE}"
            fi
            exit 0
            ;;
        -v|validate_workflow|--validate_workflow)
            _print_header "${HEADER}"
            _log_info "validating Github Actions config has same number of tests as parameters.csv:"
            cci_test_count=$(grep 'test-number: \[' ${WORKFLOW_FILE} | grep -o '[0-9]\+' | wc -l | tr -d ' ')
            if [[ "${line_count}" != "${cci_test_count}" ]]; then
                _log_error "test count mismatch!"
                rc='1'
            else
                _log_info "test count matches between workflow and parameters.csv, great success!"
                rc='0'
            fi
                _log_info_item "${WORKFLOW_FILE##*/}: ${cci_test_count} job defintions"
                _log_info_item "${PARAMS_CSV##*/}: ${line_count} test definitions"
            exit "${rc}"
            ;;
        -h|help|--help)
            _print_header "${HEADER}"
            render_help
            exit 0
            ;;
        0)
            _print_header "${HEADER}"
            _log_error "${1} is not a valid test number... exiting!"
            exit 2
            ;;
        [[:digit:]]*)
            ## Sanity check, if the line number wanted exceeds the lines in the param file, fail!
            if [[ "${1}" -gt "${line_count}" ]]; then
                echo "[ERROR] ${PARAMS_CSV} only has ${line_count} tests defined, you provided ${1}... exiting!"
                exit 1
            fi
            lines+=("${1}")
            shift
            ;;
        *)
            _log_error "${1} is an unsupported argument, please seek help...."
            render_help
            exit 1
            ;;
    esac
done

_print_header "${HEADER}"

mkdir -p "${LOG_DIR}"

if [[ "${#lines[@]}" == '0' ]]; then
    _log_error 'you need to provide which parameter csv line number(s) you want to run.... exiting!'
    exit 2
fi

## Iterate over the lines provided at run time:
for line in "${lines[@]}"; do
    declare -a cols='()'
    declare -a vars='()'
    declare -a args='()'
    line_number="${line}"

    ## Collect all the columns and populate array:
    for i in $(head -n1 "${PARAMS_CSV}" | tr , '\n'); do
        cols+=("${i}")
    done

    ## Set column count -1 as computers count from 0 not 1.
    column_count=$((${#cols[@]}-1))

    ## Collect all the parameters for the desired test line and populate array:
    for i in $(tail -n+2 $PARAMS_CSV | grep -v '^#' | sed "${line_number}q;d" | tr , '\n'); do
        vars+=("${i}")
    done

    ## Construct array of matched column and value and generate log file name:
    for i in $(seq 0 ${column_count}); do
        args+=("${cols[${i}]}=${vars[${i}]}")
    done

    ## setup the environment for the test run:
    _log_info "configuring matrix test ${line_number} of ${line_count} with the following values:"
    for i in ${args[@]}; do
        _log_info_item "${i}"
        export ${i}
    done

    echo ""
    pushd ${REPO_ROOT} 1> /dev/null
    _cmd make func-test FUNC_TEST_CONTROLS="${FUNC_TEST_CONTROLS[*]}"
    rc="${?}"
    popd 1> /dev/null

    echo ""
    if [[ ${rc} == '0' ]]; then
        _log_info "matrix test ${line_number} of ${line_count} has completed successfully with exit code ${rc}"
    else
        _log_error "matrix test ${line_number} of ${line_count} has completed with errors"
    fi
    echo ""
done

exit "${rc}"
